#! /bin/sh

###################################################################################
#
# CPMlib - Cartesian Partition Manager Library
# 
# Copyright (C) 2012-2014 Institute of Industrial Science, The University of Tokyo.
# All right reserved.
#
# Copyright (c) 2014 Advanced Institute for Computational Science, RIKEN.
# All rights reserved.
#
###################################################################################

# Copy 'cpm_Version.h' to include directory.
# If you don't have the file, do configure on other environment and copy generated one.
#
# $ make -f Makefile_spec
#
# BG/P

AR = ar rv
RANLIB = ranlib
MPICXX = mpixlcxx_r
MPI_DIR = 
TP_DIR=/hogehoge/textparser-1.2/textparser

TARGET = libcpmlib.a

SRCS = cpm_DomainInfo.cpp \
       cpm_ParaManager_frtIF.cpp \
       cpm_TextParserDomain.cpp \
       cpm_TextParser.cpp \
       cpm_ParaManager_Alloc.cpp \
       cpm_ParaManager_MPI.cpp \
       cpm_VoxelInfo.cpp \
       cpm_ParaManager.cpp

FSRCS =

.SUFFIXES: .o .c .cpp .f90

OBJS=$(SRCS:.cpp=.o)

CXXFLAGS = -O3 -qarch=450d -qtune=450 \
           -I$(MPI_DIR) \
           -I../include \
           -I$(TP_DIR)/include

FFLAGS = -I../include

$(TARGET):$(OBJS)
	$(AR) $(TARGET) $(OBJS)
	$(RANLIB) $(TARGET)

.cpp.o:
	$(MPICXX) $(CXXFLAGS) -o $@ -c $< 

clean:
	rm *.o $(TARGET)
